######################################################################
# Automatically generated by qmake (2.01a) Thu May 31 09:18:29 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 1234.c
